[links]
"lock()" = "https://docs.rs/fmutex/latest/fmutex/fn.lock.html"
"try_lock()" = "https://docs.rs/fmutex/latest/fmutex/fn.try_lock.html"
"lock_path()" = "https://docs.rs/fmutex/latest/fmutex/fn.lock_path.html"
"try_lock_path()" = "https://docs.rs/fmutex/latest/fmutex/fn.try_lock_path.html"
